### ISSUE TITLE
Primate bitsliced

### ISSUE THREAD

**Issue by opolo** [Ko-/sboxoptimization#1]
Hi Ko-,

It's some very interesting work. I am currently working on something related to it (making bit-sliced implementations of the aforementioned ciphers). 

Out of curiosity - how come you left out Primate's s-box in your paper, when it came to how effective (i.e. how low k) it could be implemented? 

My SAT solver has been running for half a day, so just curious to whether, there is some reason for you only mentioning the results of the other bitsliced s-boxes. 

Thanks!
- Jonas

**Comment by Ko-** [comment]
Hi Jonas,

Thank you for your interest. The simple reason for omitting PRIMATE in Table 3 is that I did not really manage to get any nice results there. As you can see, I found answers up to k=13 (for Keccak-chi), but for larger values of k the SAT solvers quickly did not terminate anymore within reasonable time.

However, there is probably room for improvement (e.g. finetuning SAT solver settings), so if you do find something, the PRIMATEs team (and I) would certainly be interested to hear about it.

Best regards,
Ko
