### ISSUE TITLE
Rectangle gc with k=11

### ISSUE THREAD

**Issue by siweisun** [Ko-/sboxoptimization#2]
Hi Ko-,

I'm try to do the experiment for the Rectangle S-Box (gc, k=11).
My SAT solver have running about 1 day long on the linux virtual machine without finding the solution.
Is this normal or maybe I made some mistake?

Thank you very much.

Siwei Sun

**Comment by Ko-** [comment]
Dear Siwei,

That particular one took me 54.6 hours and around 10 GB of RAM, so yes, I'm afraid it's normal. The same computation for the inverse RECTANGLE S-box took only 3.7 hours and 1.5 GB RAM, however. It really varies greatly. Anyway, I wouldn't recommend to do this in a virtual machine.

Best regards,
Ko

**Comment by siweisun** [comment]
Get it. Thank you very much!   : )
